# 项目相关配置
milocweb:
  # 名称
  name: MiloWeb
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2019
  # 文件上传路径
  profile: D:/profile/

# 开发环境配置
server:
  port: 8888
  servlet:
    # 项目contextPath
    context-path: /miloweb


  # 模板引擎
spring:
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
    prefix: classpath:/templates/views/
    suffix: .html