#项目相关配置
milocweb:
  #名称
  name: MiloWeb
  #年份
  version: 1.0.0
  #版权年份
  copyrightYear: 2019
  #文件上传路径
  profile: D:/profile/

#开发环境配置
server:
  port: 8888
  servlet:
    context-path: /miloweb


#模板引擎
spring:
  thymeleaf:
    mode: HTML
    encoding: utf-8
    #禁用缓存
    cache: false
    prefix: classpath:/templates/views/
    suffix: .html
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true

#资源路径
web:
  #静态资源
  staticUrl: http://www.milogenius.com/static/
  #文件上传
  uploadFileUrl:
  #全局地址
  globalUrl: http://www.milogenius.com/miloweb/