
# 开发环境配置
server:
  port: 8084
  servlet:
    # 项目contextPath
    context-path: /milo


spring:
   application:
   name: spirng-boot-rabbitmq-receiver
   #rabbitmq配置
   rabbitmq:
   host: 127.0.0.1
   port: 5672
   username: guest
   password: guest

